### PR TITLE
Update to use yaml-rust2 instead of yaml-rust

### PR DESCRIPTION
**Pull request by ZimboPro**
Updated dependencies to use `yaml-rust2` instead of `yaml-rust` and necessary changes to tests and dependencies where needed

### CODE REVIEW

**Comment by qtfkwk** [comment]
Thanks for putting this together! Have a few notes/questions:

* Why replace linked-hash-map with hashlink?
* The changes to the tests are not appropriate since the intention is to maintain the original ordering rather than put new keys at the bottom. https://github.com/qtfkwk/merge-yaml-hash/issues/1 Unsure if this is caused by hashlink?
* Would love to apply this to merge-yaml-hash as I'm the one who nudged the yaml-rust => yaml-rust2 thing...
* You might also consider modifying any dependent code to use https://github.com/qtfkwk/yaml-hash instead of this crate since it is effectively a rebuilt version of this crate that already uses yaml-rust2

**Comment by ZimboPro** [comment]
> Why replace linked-hash-map with hashlink?

yaml-rust2 uses the hashlink crate and not linked-hash-map, even though it seems to use the same enum, due to being in different crates, it would not work, hence I had to use the one that yaml-rust2 uses

**Comment by ZimboPro** [comment]
> The changes to the tests are not appropriate since the intention is to maintain the original ordering rather than put new keys at the bottom. https://github.com/qtfkwk/merge-yaml-hash/issues/1 Unsure if this is caused by hashlink?

It most likely is caused by hashlink, there is a newer version but it did not want to compile with the latest

> You might also consider modifying any dependent code to use https://github.com/qtfkwk/yaml-hash instead of this crate since it is effectively a rebuilt version of this crate that already uses yaml-rust2

I did not know this existed. I was already using merge-yaml-hash before yaml-rust2 was released.

**Comment by ZimboPro** [comment]
I can close the PR since there is already a crate that exists using the yaml-rust2 crate. Would you prefer that I did?

**Comment by qtfkwk** [comment]
Yes. Assuming yaml-hash works for your use case, it is the better path. Please do let me know via an issue on that project if you have any issue. Thanks!

**Pull request closed without merging**
